### PR TITLE
Add getting started to readme

### PR DESCRIPTION
**Pull request by DC00**

### CODE REVIEW

**Comment by jnayak1** [comment]
Hey, the repo got a little messed up with master vs. develop. I'm going to fix it but I'm not going to be able to pull your commit in since things have been pushed to master that aren't in develop. I'll copy what you added into the README though.

**Comment by DC00** [comment]
When I clone the master branch, I just see a readme. What should I do?

**Comment by DC00** [comment]
Oh I see. Are you keeping the dev branch as the root?

**Comment by jnayak1** [comment]
I think we are going to have to delete the dev branch and then create a new dev branch off of master because its diverged so much.

**Comment by jnayak1** [comment]
Or I guess we could just reset the develop branch to the last place it was with master and then pull master

**Comment by jnayak1** [comment]
Nevermind, develop needs to be deleted and recreated

**Pull request closed without merging**
